LOAD_DATA:
  Historical_price:
    [
      'time', 
      'open', 
      'high', 
      'low', 
      'close', 
      'volume', 
      'ticker',
      ]

DATA_PURPOSE:
  Historical_price:
    num_cols:
      [
      'open', 
      'high', 
      'low', 
      'close', 
      'volume', 
      ]
    cat_cols:
      [
        'ticker',
      ]
    date_cols:
      [
        'time',
      ]